### ISSUE TITLE
App crashes when login button is clicked when username and  password fields are empty

### ISSUE THREAD

**Issue by neeraj0403** [openMF/android-client#1347]
**Summary:** 

when  a user  open the app and directly click on login button the app get crashed 

**Steps to reproduce:** 
1.open the app
2.directly click on login button 
3.app will get crashed

**Expected behaviour:** 

instead of crashing of the app,the user  see a toast message to fill the details and focus on the username and password edittext to fill it 

**Observed behaviour:** 
but here the app is getting crashed ,when we directly click the login button

**Device and Android version:** 

Redmi 6
Android 9

**Screenshots:** 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/45105688/75570843-071de400-5a7e-11ea-9134-564a849d430e.gif)

**Comment by neeraj0403** [comment]
i am going to solve it

**Comment by neeraj0403** [comment]
i will work on this issue .

**Comment by RajaVamsi11** [comment]
@neeraj0403 Can you please specify the version of your Android phone because it was working fine in my device. A snack bar is being displayed when the username and password are empty. 


![Screenshot_2020-02-28-23-38-56-722_com mifos mifosxdroid](https://user-images.githubusercontent.com/30550059/75573831-aa252c80-5a83-11ea-9d48-b1aa15edbed6.jpg)

**Comment by neeraj0403** [comment]
@RajaVamsi11 just simply open the app and directly click on the login button
