### ISSUE TITLE
WARNING Observed in fragment_client.xml

### ISSUE THREAD

**Issue by NikunjGarg2000** [openMF/android-client#1718]
**Summary:** 

Android Studio shows that for vector drawables srcCompat is used.

**Steps to reproduce:** 

Just change android:src to app:srcCompat

**Device and Android version:** 

 ALL

**Screenshots:** 

![1](https://user-images.githubusercontent.com/67901968/104834810-d8903e00-58c7-11eb-8ec3-a94654ff7d0e.png)

**Comment by danishjamal104** [comment]
Avoid creating issues for such small things if you want to resolve warnings then create an issue targeting more xmls since there are many files which have warning and it needs to be removed. 
So what you can do is fix the warning in 2-5 XML in this way this issue would play a significant role.
But for now, this is fine. Just keep this thing in mind for next time. Thank you.:)

**Comment by NikunjGarg2000** [comment]
Ok @danishjamal104 , Thank you I will definitely improve on this.
