### ISSUE TITLE
Handle Errors gracefully for Data calls from the API 

### ISSUE THREAD

**Issue by ishan1604** [openMF/android-client#287]
Toast messages should not be thrown from Data Helpers etc. Since it is an android component we must abstract that layer out. 

Possibly create a layer that throws Toasts from the stored error messages.

**Comment by mayank-kgp** [comment]
@ishan1604 
Can you please explain this issue in detail?
@therajanmaurya  Can u help me in this issue?

**Comment by therajanmaurya** [comment]
This issue was about to handle the Toast message in SaveOfflineDataHelper in the [commit](https://github.com/openMF/android-client/commit/e3dc5c76495b60c01b4194d8a184bd3a856ef5b2#diff-3894850408456c9624080ec09afad09fR182).
This helper class has been removed because I have written the Database layer separately that is binded with the DataManager, that's why this helper class making no sense and no use. So It has been removed.
