### ISSUE TITLE
Overlapping of Dashboard  screen

### ISSUE THREAD

**Issue by reverie-ss** [openMF/android-client#397]
**Summary:** 

Summarize your issue in one sentence (what goes wrong, what did you expect to happen)

**Steps to reproduce:** 

options-> create client -> groups(nav bar) -> back button

**Expected behavior:** 

To show only the dashboard

**Observed behavior:** 

The dashboard was overlapped on previous page

**Device and Android version:** 

Device- YU Yureka+
Android Version - 6.0.1 Marshmallow (Custom ROM)

**Screenshots:**
![mifosxdroidbug](https://cloud.githubusercontent.com/assets/14177137/20267364/61c161e8-aaa0-11e6-8f6f-6e3918302770.png)

**Comment by therajanmaurya** [comment]
@reverie-ss Good Job, Feel free to open PR. Thanks for finding Bug 👍.

**Comment by yvsssantosh** [comment]
@therajanmaurya @reverie-ss 
Is this issue open..? If yes i'd like to work on it

Thanks

**Comment by reverie-ss** [comment]
@yvsssantosh 
Yes, this is open!
I am working on it. I will continue once my exams are over.
Please feel free to contribute!

**Comment by SKrPl** [comment]
@therajanmaurya @reverie-ss I solved the issue but while doing the ./gradlew check, I am getting an error "Dodgy coding warning" i.e. Write to static field from instance method. What should I do so that i don't get that error ??

![screenshot_20170102_183523](https://cloud.githubusercontent.com/assets/12163892/21589677/5839aaae-d11a-11e6-8bd2-a22b7e0fe0e9.png)

**Comment by therajanmaurya** [comment]
fixed in #519
