### ISSUE TITLE
Items in option menu are not stable

### ISSUE THREAD

**Issue by mayank-kgp** [openMF/android-client#476]
**Summary:** 

If we click on any menu item in Dashboard Activity and come back then menu item is disappeared that was clicked before.

**Steps to reproduce:** 

1. Click on menu item in dashboard activity. There are 4 menu items.
2. Come back to dashboard activity. Now only three menu items are there.

**Expected behavior:** 

Menu items should not change.

**Observed behavior:** 

The clicked menu item disappears after coming back to Dashboard Activity.

**Device and Android version:** 

Yureka with android 5.1.1

**Comment by mayank-kgp** [comment]
@therajanmaurya I would like to work on.

**Comment by tarun0** [comment]
It was implemented as the fix for https://github.com/openMF/android-client/issues/427 in https://github.com/openMF/android-client/pull/439 But yes, I also think that it's a potential bug.

**Comment by therajanmaurya** [comment]
@mayank-kgp I want some more changes on this issue. 
1. Revert the work done in #439.
2. Add functionality. If the user clicks on any menu item, then disable the menu button not invisible.
3. If the user will clicks on Navigation drawer item then make click able all dashboard menu options.

**Comment by karsai1993** [comment]
Hi! I would like to work on this but as I started to use the application and have a look at the code, I faced that none of the three points suggested by @therajanmaurya is done. My version of the code is quite fresh (forked 3 days ago). So, I start to implement my solution idea.

**Comment by karsai1993** [comment]
Hi! I have finished the implementation and it fulfills the requirements above. Here is what I have done to solve the problem shown through the three points suggested by @therajanmaurya .
1, I think not the whole work should be reverted because the methods, which were declared to determine which menu button should not be able to be selected, are useful as described in next point.
2, In case of handling create group fragment, the method we use is the following:
private void setMenuCreateGroup(boolean visibility) {
        if (menu != null) {
            //position of mItem_create_new_group is 2
            menu.getItem(2).setVisible(visibility);
        }
    }
I suppose above code was declared by the previous code. We can use it but we have to implement a little modification:
private void setMenuCreateGroup(boolean isEnabled) {
        if (menu != null) {
            //position of mItem_create_new_group is 2
            menu.getItem(2).setEnabled(isEnabled);
        }
    } 
So, we need to change "setVisible" to "setEnabled" and (not to lead the reader of the code to misunderstanding) "visibility" to "isEnabled". It is true for create client and create center, too.
3, I think clicking to Navigation drawer item is not enough to solve the problem. Explanation: let's suppose we are in the e.g.: create client activity. Then Navigation drawer item is clicked (alternatively all the menu buttons become enabled) but if we click back button of our device, we get back to create client. As it was defined that in this case the menu button of create client should be disabled, we would face another bug because we clicked to Navigation drawer button, so we made all the menu buttons enabled. 
That's why my implementation is the following: it focuses on perfoming the process of making the menu buttons enabled in the onBackPressed method as below:
@Override
    public void onBackPressed() {
        // check if the nav mDrawer is open
        if (mDrawerLayout != null && mDrawerLayout.isDrawerOpen(GravityCompat.START)) {
            mDrawerLayout.closeDrawer(Gravity.LEFT);
        } else {
            setMenuCreateClient(true);
            setMenuCreateCentre(true);
            setMenuCreateGroup(true);
            super.onBackPressed();
        }
    }
So, all the menu buttons are made to be enabled when we get back from one of the fragments to the DashboardActivity by clicking back button. They are also get become enabled when we enter DashboardActivity from Navigation drawer.

I hope it was clear.
I am ready to commit and create a pull request.
What do you think?

Best Regards,
Laszlo Karsai

**Comment by luckyman20** [comment]
@therajanmaurya I think this issue should be closed as it solved in #580
