### ISSUE TITLE
Issue with 'Repaid Every' field in Add loan account for client

### ISSUE THREAD

**Issue by santoshmath** [openMF/android-client#693]
1. Go to any client page and tap on right top corner and then tap on Add Loan Account 
2. On loan application page, select 'Repaid Every' as 1 month
> If you we select Repaid Every as 1 month , it's compulsory that , I have to select the First Sunday, or Second Monday, so on. But this is not compulsory on Web -app.
Check the screenshots
Web-app:
![webapp](https://user-images.githubusercontent.com/23022667/26915166-9b22be2a-4c42-11e7-8b0e-628f6c170ef9.png)

Andriod-app:
![androidapp](https://user-images.githubusercontent.com/23022667/26915177-a5d420f2-4c42-11e7-9f9f-71b142ada5ca.png)

**Comment by mayank-kgp** [comment]
@therajanmaurya Can I work on this?

**Comment by mayank-kgp** [comment]
@santoshmath I am not facing any issue in my device. Can you please tell me the exact options which you are checking on?
@tarun0 Can you please check once? If you are facing any issue.

**Comment by tarun0** [comment]
@mayank-kgp The month and week should be optional in the app which they are not, at present.

**Comment by mayank-kgp** [comment]
Ok. I will see into it.

**Comment by mayank-kgp** [comment]
@tarun0 First sunday is automatically selected. How is the idea of put "Select" in the spinner like 
"Link Savings" spinner?

**Comment by tarun0** [comment]
@mayank-kgp I added a new string value at the end of the retrieved list of the savings accounts. While submitting the application, I checked the value at that position. If it's 'Select Account', the linked saving is set to null, otherwise, it's set to the value of the selected account.

Check https://github.com/openMF/android-client/blob/master/mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountFragment.java#L494 and https://github.com/openMF/android-client/blob/master/mifosng-android/src/main/java/com/mifos/mifosxdroid/online/loanaccount/LoanAccountFragment.java#L646
