### ISSUE TITLE
Client Profile Pictures not showing on Android App

### ISSUE THREAD

**Issue by datadve** [openMF/android-client#739]
@therajanmaurya 

The Client profile Pictures aren't showing on Android App after upload, though it updates on the Community web App.

**Comment by edcable** [comment]
@therajanmaurya do we have any updates on this? @tarun0 Could you look into fixing this issue for David? He's been awaiting a fix on it.

**Comment by mayank-kgp** [comment]
@edcable I think this is the same issue as #725 .
I have resolved it in #735 .
Please have a look at GIF after resolving it. 
https://github.com/openMF/android-client/pull/735#issuecomment-319422008

**Comment by therajanmaurya** [comment]
I was thought @mayank-kgp fixed worked, Let me an hour I am working on it.

**Comment by mayank-kgp** [comment]
@therajanmaurya I have checked again, it is working fine. Please let me know if you feel that we should change something else.

**Comment by therajanmaurya** [comment]
@datadve I think, the code you are using, It does not contain the PR in which this has been fixed. Please the PULL the code again and run. It's working fine now. 

One thing can bother you that whenever you update the image in client details section and come back to client list again. It will not show, till that you will not refresh the list again. 

I am making the fix for that now and let you know too.

**Comment by therajanmaurya** [comment]
@datadve @edcable It's solved, I am sending the PR and will merge. Now as you will update the client image in details activity and will come back to client list. It will automatically update. 

Thanks again @datadve for reporting the issue.

**Comment by therajanmaurya** [comment]
Fixed in #749
