### ISSUE TITLE
Requesting for Scrolling Bar on Client/Group/Centers Listing 

### ISSUE THREAD

**Issue by fboniphace** [openMF/android-client#778]
Also There is a need to implement a Scrolling Bar on Client/Group/Centers Listing so as to show the approximate the position and length of the listing, So this can can positively impact the Navigation through the Listing.
Thanks

**Comment by luckyman000786** [comment]
@edcable @therajanmaurya Can I work on this issue ?

**Comment by therajanmaurya** [comment]
@fboniphace @luckyman000786 issue description is sufficient to know what you want to do. Please expand.

**Comment by bensoft2k5** [comment]
@luckyman000786 did you create a pull request for this?

**Comment by luckyman000786** [comment]
@therajanmaurya According to me, this description is sufficient me to understand. It simply says that Clients/Groups/Centers Listing should have scrollbar so the user has an idea how big is the list and where the user is currently located in the list

@bensoft2k5 No, I haven't created a pull request for this issue as this issue is not assigned to me yet. Although I have made the solution in my local machine
