### ISSUE TITLE
Typos in issue Template.

### ISSUE THREAD

**Issue by ivary43** [openMF/android-client#838]
**Summary:** 

There are typos in Issue Template (word behaviour is misspelt).

**Screenshots**
![oie_77h7rxlcfuar](https://user-images.githubusercontent.com/24601454/35932123-db171550-0c5c-11e8-9d03-2aef9b3548da.png)

I am working on this issue.

**Comment by AkshGautam** [comment]
@ivary43 This is not a Typo.There is a set of conventions for British English and American English. Its the same thing as "color" or "colour" even "theater" or "theatre". Both are well accepted. Behavior (American English) or behaviour (Commonwealth English) is both valid and I think behavior would be much accepted since we use American English on daily basis instead of British.

**Comment by ivary43** [comment]
@AkshGautam I think Commonwealth English is preferred everywhere as you can see here[http://grammarist.com/spelling/behavior-behaviour/](url) and at many places if you google.

**Comment by AkshGautam** [comment]
@ivary43  That's a personal preference. Both are acceptable, nothing is right or wrong in this context. It's @therajanmaurya  final call. My only proposition was that it is not a typo but a matter of personal opinion.

**Comment by ivary43** [comment]
Closed by PR #840 .
