### ISSUE TITLE
Search feature in client section

### ISSUE THREAD

**Issue by prem0862** [openMF/android-client#887]
**Summary:** 

Search feature for client in client section

**Steps to reproduce:** 

Navigation drawer -> Client

**Screenshots:** 
![screenshot 234](https://user-images.githubusercontent.com/25509407/36134605-dc612b78-10ab-11e8-9a6b-a6500647a7c2.png)

**Comment by Prem0707** [comment]
@luckyman20 @tarun0 Your's views on it?

**Comment by luckyman20** [comment]
@Prem0707 Please tell your approach.

**Comment by Prem0707** [comment]
Now, in our application, there is search feature on the dashboard. Whenever we are looking for a client then we must have to return to the dashboard but what we can do is we can also implement search feature in client section, there we can search a client by his/her name (or some extra parameter) so that we will save a lot of time in scrolling (for a client) and it will also enhance user experience.

**Comment by AkshGautam** [comment]
@Prem0707 The discussion for something similar went in #785 where @tarun0 made a sound proposition. Looking at that issue might be helpful.Though it was a different issue the discussion in the comments might be helpful. Thanks

**Comment by luckyman20** [comment]
@AkshGautam Searching and Sorting are two different things. 

@Prem0707 I think you can go ahead but after we get the views of @therajanmaurya , @dilpreet96 or @tarun0 . Currently, we should only do for client's name. Later, we can think of the other parameters too.

**Comment by AkshGautam** [comment]
@luckyman20 surely searching and sorting are different things but why do we sort things? to make search easier so both are somehow related since sorting makes search easier until and unless we are using an advanced data structure such as Trie. I just felt that these issues had something in common so I just gave a pointer. According to me this would definitely be a good addition, I just gave a pointer to something similar. Thanks

**Comment by luckyman20** [comment]
@AkshGautam I totally agree with you and I think both the things (searching and sorting) will help a lot user to easily find a client from such a big list.

**Comment by AkshGautam** [comment]
@luckyman20  I believe that too.

**Comment by Prem0707** [comment]
@luckyman20I will wait for @therajanmaurya @dilpreet96 or @tarun0 views on it.
@AkshGautam what I believe is sorting will, of course, make things easier to some extent but in case of the larger database, we will have to scroll so many screens, in that case, the search will definitely make our work easier. What do you say?

**Comment by AkshGautam** [comment]
I agree with you. I was never against this feature. I just pointed out a previous proposition.

**Comment by Prem0707** [comment]
@luckyman20 can we use some library search like MaterialSearchView?

**Comment by luckyman20** [comment]
@Prem0707 You can use but explain why we need it

**Comment by Prem0707** [comment]
@luckyman MaterialSearchView is a library to implement SearchView in a Material Design Approach.

**Comment by luckyman20** [comment]
@Prem0707 You can go for it if it works well with the Current UI

**Comment by tarun0** [comment]
@Prem0707 This isn't really needed. The search feature is already there on the home screen! @AkshGautam Since we are using pagination, sorting doesn't make much sense unless all the data is loaded which will only happen when the user (the field officer) has scrolled to the bottom.

**Comment by Prem0707** [comment]
@tarun @luckyman Please close this issue, if we don't need it. Thanks
